version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - 8080:80
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:8.1.0
    volumes:
      - ./bbdd:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      wordpress:
        aliases:
          - mysql

networks:
  wordpress:
